# Generated by Django 6.1 on 2026-09-01 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_color', models.CharField(default='#6366f1', max_length=7)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=64)),
                ('currency', models.CharField(choices=[('BDT', '৳ BDT'), ('USD', '$ USD'), ('EUR', '€ EUR'), ('GBP', '£ GBP')], default='BDT', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
